
// -*- C++ -*-
// $Id: Version.h 95202 2011-12-04 10:53:13Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 0
#define ACE_BETA_VERSION 6
#define ACE_VERSION "6.0.6"
